app:
  name: rai
auth:
  provider: auth0
  domain: raiproject.auth0.com
  client_id: ==AES32==59Eg6+hFDfkoeZCkQvSUo0sgCsHcu1B9MoGgANkwyzJqgtVfQr7IG6iY+awG8abQPUmnaaAqJrYfbtxO
  client_secret: ==AES32==2pOhrh3oRAs+o6h1Z7kcM4w6LpFjL67+j2vBTMGpS91jtBO42wKGjkIUTCtqUukMy2K/5VmzL125YcuPnwiVbZiwXTrmr8O/gW8H/DOGEWCjI5dqcaHhIsMFVEWT5GNbw1/moxb4sF4=
